<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTblMasterDivisi extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbl_master_divisi', function (Blueprint $table) {
            $table->id();
            $table->integer('unit_kerja_id');
            $table->text('nama_divisi');
        });

        //insertDatatoTable'tbl_master_divisi'
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '22', 'nama_divisi' => 'Divisi Transaksi Pinjaman']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '22', 'nama_divisi' => 'Divisi Legal & Administrasi Pinjaman']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '22', 'nama_divisi' => 'Divisi Hubungan Bisnis Korporasi Non BUMD']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '22', 'nama_divisi' => 'Divisi Data & Dokumen Pinjaman']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '22', 'nama_divisi' => 'Divisi Kebijakan Non Bisnis']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '4', 'nama_divisi' => 'Divisi Sistem Akuntansi']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '4', 'nama_divisi' => 'Divisi Kredit Kepemilikan Rumah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '4', 'nama_divisi' => 'Divisi Kredit Mikro II']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '4', 'nama_divisi' => 'Divisi Keuangan & Pelaporan']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Divisi Manajemen Audit']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Divisi Audit Umum']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Kantor Kas Tropodo']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Divisi Branchless Banking']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Divisi Audit Teknologi Informasi']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Divisi Cash & Trade Operation']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '7', 'nama_divisi' => 'Divisi Audit Investigasi & Anti Fraud']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '14', 'nama_divisi' => 'Divisi Digital Banking']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '14', 'nama_divisi' => 'Divisi Digital Banking Ecosystem']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '21', 'nama_divisi' => 'Divisi Hubungan Pemerintah Provinsi DKI Jakarta']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '21', 'nama_divisi' => 'Divisi Legal & Administrasi Pinjaman']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '21', 'nama_divisi' => 'Divisi Pengadaan TI']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '21', 'nama_divisi' => 'Divisi Hubungan Bisnis Ekosistem BUMD']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '21', 'nama_divisi' => 'Divisi Hubungan Bisnis Korporasi Non BUMD']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '21', 'nama_divisi' => 'Divisi Digital Banking Ecosystem']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '11', 'nama_divisi' => 'Divisi Litigasi']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '11', 'nama_divisi' => 'Divisi Manajemen Kinerja & Project Management Office']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '11', 'nama_divisi' => 'Divisi Hukum Korporasi & Perkreditan']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '20', 'nama_divisi' => 'Divisi Kebijakan Bisnis']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '20', 'nama_divisi' => 'Divisi Kebijakan Non Bisnis']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '20', 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer, Mikro & Ritel']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '10', 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Ritel']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '10', 'nama_divisi' => 'Divisi Tata Kelola & APU-PPT']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '10', 'nama_divisi' => 'Divisi Operasional Manajemen SDM']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '10', 'nama_divisi' => 'Divisi Review Kepatuhan']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '57', 'nama_divisi' => 'Divisi Kredit Komersial']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '6', 'nama_divisi' => 'Divisi Kredit Multi guna']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '6', 'nama_divisi' => 'Divisi Dana & Jasa']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '6', 'nama_divisi' => 'Divisi Kredit Kepemilikan Rumah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '6', 'nama_divisi' => 'Divisi IT Project Management']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '12', 'nama_divisi' => 'Divisi Kredit Mikro II']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '58', 'nama_divisi' => 'Divisi Kredit Ritel I']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '58', 'nama_divisi' => 'Divisi Kredit Ritel II']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '9', 'nama_divisi' => 'Divisi Risiko Operasional, Lainnya, dan Pelaporan']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '9', 'nama_divisi' => 'Divisi Risiko Kredit, Pasar, dan Likuiditas']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '17', 'nama_divisi' => 'Divisi Branchless Banking']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '17', 'nama_divisi' => 'Divisi Customer Care']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '17', 'nama_divisi' => 'Divisi Cash Pooling Center']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '17', 'nama_divisi' => 'Divisi Cash & Trade Operation']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '3', 'nama_divisi' => 'Divisi Pengelolaan Aset dan Layanan Umum']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '3', 'nama_divisi' => 'Divisi Pengadaan Non-TI']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '3', 'nama_divisi' => 'Divisi Pengadaan TI']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '18', 'nama_divisi' => 'Divisi Bisnis Cabang']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '18', 'nama_divisi' => 'Divisi Layanan Cabang']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '18', 'nama_divisi' => 'Divisi Pendukung Cabang']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '18', 'nama_divisi' => 'Divisi Jaringan Kantor']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '23', 'nama_divisi' => 'Divisi Pengelolaan Produk & Portofolio']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '23', 'nama_divisi' => 'Divisi Bisnis Dana Ritel & Komunitas']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '23', 'nama_divisi' => 'Divisi Transaction Banking']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '19', 'nama_divisi' => 'Divisi Manajemen Kinerja & Project Management Office']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '19', 'nama_divisi' => 'Divisi Perencanaan & Pengembangan']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '16', 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Menengah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '16', 'nama_divisi' => 'Divisi Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer, Mikro & Ritel']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '16', 'nama_divisi' => 'Divisi Lelang & Portfolio Management']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '15', 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Menengah & Komersial I']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '15', 'nama_divisi' => 'Divisi Risiko Kredit/Pembiayaan Ritel']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '2', 'nama_divisi' => 'Divisi Learning Center']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '2', 'nama_divisi' => 'Divisi Strategi & Kebijakan Manajemen SDM']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '2', 'nama_divisi' => 'Divisi Pengembangan & Budaya']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '2', 'nama_divisi' => 'Divisi Operasional Manajemen SDM']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '59', 'nama_divisi' => 'Divisi Pembiayaan Menengah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '59', 'nama_divisi' => 'Divisi Pembiayaan Konsumer']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '59', 'nama_divisi' => 'Divisi Pembiayaan Mikro & Ritel']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '59', 'nama_divisi' => 'Divisi Dana & Jasa']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '1', 'nama_divisi' => 'Divisi IT Development']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '1', 'nama_divisi' => 'Divisi IT Operation']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '1', 'nama_divisi' => 'Divisi IT Governance, Risk & Control']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '1', 'nama_divisi' => 'Divisi IT Business Analyst']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '1', 'nama_divisi' => 'Divisi IT Project Management']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '5', 'nama_divisi' => 'Divisi Banking Management dan ALMA']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '5', 'nama_divisi' => 'Divisi Global Market']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '8', 'nama_divisi' => 'Divisi Kesekretariatan']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '8', 'nama_divisi' => 'Divisi Komunikasi Pemasaran']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '60', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '61', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '62', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '63', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '64', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '65', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '66', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '67', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '68', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '69', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '70', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '71', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '72', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '73', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '74', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '75', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '76', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '77', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '78', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '79', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '80', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '81', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '82', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '83', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '84', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '85', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '86', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '87', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '88', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '89', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '90', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '91', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '92', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '93', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '94', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '95', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '96', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '97', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '98', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '99', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '100', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '101', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '102', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '103', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '104', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '105', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '106', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '107', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '108', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '109', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '110', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '111', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '112', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '113', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '114', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '115', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '116', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '117', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '118', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '119', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '120', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '121', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '122', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '123', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '124', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '125', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '126', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '127', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '128', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '129', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '130', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '131', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '132', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '133', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '134', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '135', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '136', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '137', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '138', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '139', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '140', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '141', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '142', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '143', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '144', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '145', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '146', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '147', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '148', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '149', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '150', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '151', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '152', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '153', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '154', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '155', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '156', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '157', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '158', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '159', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '160', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '161', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '162', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '163', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '164', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '165', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '166', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '167', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '168', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '169', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '170', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '171', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '172', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '173', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '174', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '175', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '176', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '177', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '178', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '179', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '180', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '181', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '182', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '183', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '184', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '185', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '186', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '187', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '188', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '189', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '190', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '191', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '192', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '193', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '194', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '195', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '196', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '197', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '198', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '199', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '200', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '201', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '202', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '203', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '204', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '205', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '207', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '206', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '208', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '209', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '210', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '212', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '213', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '214', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '215', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '216', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '217', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '218', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '219', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '220', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '221', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '222', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '223', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '224', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '225', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '226', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '227', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '228', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '229', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '230', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '231', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '232', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '233', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '234', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '235', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '236', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '237', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '238', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '239', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '240', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '241', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '242', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '243', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '244', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '245', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '246', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '247', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '248', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '249', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '250', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '251', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '253', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '252', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '254', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '255', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '256', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '257', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '258', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '259', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '260', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '261', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '262', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '263', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '264', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '265', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '266', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '267', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '268', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '269', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '270', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '271', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '272', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '273', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '274', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '275', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '276', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '277', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '278', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '279', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '280', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '281', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '282', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '283', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '284', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '285', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '286', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '287', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '288', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '289', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '290', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '291', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '292', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '293', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '294', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '295', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '296', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '297', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '298', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '299', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '300', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '301', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '302', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '303', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '304', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '305', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '306', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '307', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '308', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '309', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '310', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '311', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '312', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '313', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '314', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
        DB::table('tbl_master_divisi')->insert(['unit_kerja_id' => '315', 'nama_divisi' => 'Bidang Pelayanan Nasabah']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbl_master_divisi');
    }
}
