<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTblMasterDepartemen extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbl_master_departemen', function (Blueprint $table) {
            $table->id();
            $table->integer('unit_kerja_id');
            $table->integer('divisi_id');
            $table->text('nama_departemen');
        });

        //insert data to table
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '1', 'nama_departemen' => 'Departemen Pencairan Pinjaman']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '1', 'nama_departemen' => 'Departemen Transaksi Batch Loan & Bank Garansi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '1', 'nama_departemen' => 'Departemen Fasilitas Pinjaman']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '2', 'nama_departemen' => 'Departemen Review Legal Dokumen Pinjaman']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '3', 'nama_departemen' => 'Departemen Review Legal Dokumen Pinjaman']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '2', 'nama_departemen' => 'Departemen Akad']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '3', 'nama_departemen' => 'Departemen Akad']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '3', 'nama_departemen' => 'Unit Sentral Administrasi Kredit & Pembiayaan Kantor Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '2', 'nama_departemen' => 'Unit Sentral Administrasi Kredit & Pembiayaan Kantor Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '4', 'nama_departemen' => 'Departemen Pengelolaan Data & Pelaporan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '5', 'nama_departemen' => 'Departemen Pengelolaan Data & Pelaporan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '5', 'nama_departemen' => 'Departemen Legal & Dokumentasi Pinjaman']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '22', 'divisi_id' => '4', 'nama_departemen' => 'Departemen Legal & Dokumentasi Pinjaman']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '6', 'nama_departemen' => 'Departemen Anggaran']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '7', 'nama_departemen' => 'Departemen Anggaran']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '7', 'nama_departemen' => 'Departemen Sistem Akuntansi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '6', 'nama_departemen' => 'Departemen Sistem Akuntansi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '7', 'nama_departemen' => 'Departemen Akuntansi Syariah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '6', 'nama_departemen' => 'Departemen Akuntansi Syariah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '8', 'nama_departemen' => 'Departemen Pengelolaan Pembayaran']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '9', 'nama_departemen' => 'Departemen Pengelolaan Pembayaran']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '8', 'nama_departemen' => 'Departemen Perpajakan Korporasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '9', 'nama_departemen' => 'Departemen Perpajakan Korporasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '9', 'nama_departemen' => 'Departemen Pelaporan Regulator']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '8', 'nama_departemen' => 'Departemen Pelaporan Regulator']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '8', 'nama_departemen' => 'Departemen Pelaporan Keuangan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '4', 'divisi_id' => '9', 'nama_departemen' => 'Departemen Pelaporan Keuangan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '10', 'nama_departemen' => 'Departemen Manajemen Audit']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '10', 'nama_departemen' => 'Departemen Kendali Mutu & Pengembangan Audit']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '11', 'nama_departemen' => 'Unit Audit Umum']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '12', 'nama_departemen' => 'Unit Audit Umum']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '13', 'nama_departemen' => 'Unit Audit Teknologi Informasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '14', 'nama_departemen' => 'Unit Audit Teknologi Informasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '15', 'nama_departemen' => 'Unit Audit Investigasi & Anti Fraud']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '7', 'divisi_id' => '16', 'nama_departemen' => 'Unit Audit Investigasi & Anti Fraud']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '14', 'divisi_id' => '17', 'nama_departemen' => 'Unit Digital Banking Improvement']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '14', 'divisi_id' => '18', 'nama_departemen' => 'Unit Business Alliance']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '14', 'divisi_id' => '18', 'nama_departemen' => 'Unit Banking Ecosystem']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '21', 'divisi_id' => '19', 'nama_departemen' => 'Unit Hubungan Pemerintah Provinsi DKI Jakarta']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '21', 'divisi_id' => '20', 'nama_departemen' => 'Unit Hubungan Pemerintah Provinsi DKI Jakarta']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '21', 'divisi_id' => '21', 'nama_departemen' => 'Unit Hubungan Bisnis Ekosistem BUMD']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '21', 'divisi_id' => '22', 'nama_departemen' => 'Unit Hubungan Bisnis Ekosistem BUMD']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '21', 'divisi_id' => '23', 'nama_departemen' => 'Unit Hubungan Bisnis Korporasi Non BUMD']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '21', 'divisi_id' => '24', 'nama_departemen' => 'Unit Hubungan Bisnis Korporasi Non BUMD']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '25', 'nama_departemen' => 'Departemen Litigasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '25', 'nama_departemen' => 'Departemen Administrasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '26', 'nama_departemen' => 'Departemen Hukum Perkreditan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '27', 'nama_departemen' => 'Departemen Hukum Perkreditan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '27', 'nama_departemen' => 'Departemen Hukum Bisnis & Operasional']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '26', 'nama_departemen' => 'Departemen Hukum Bisnis & Operasional']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '27', 'nama_departemen' => 'Departemen Hukum Korporasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '11', 'divisi_id' => '26', 'nama_departemen' => 'Departemen Hukum Korporasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '20', 'divisi_id' => '28', 'nama_departemen' => 'Departemen Kebijakan Kredit / Pembiayaan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '20', 'divisi_id' => '28', 'nama_departemen' => 'Departemen Kebijakan Dana, Jasa dan Tresuri']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '20', 'divisi_id' => '29', 'nama_departemen' => 'Departemen Kebijakan Operasional']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '20', 'divisi_id' => '30', 'nama_departemen' => 'Departemen Kebijakan Operasional']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '31', 'nama_departemen' => 'Unit Review Bisnis']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '32', 'nama_departemen' => 'Unit Review Bisnis']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '32', 'nama_departemen' => 'Unit Review Non-Bisnis']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '31', 'nama_departemen' => 'Unit Review Non-Bisnis']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '33', 'nama_departemen' => 'Departemen Manajemen Kepatuhan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '34', 'nama_departemen' => 'Departemen Manajemen Kepatuhan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '34', 'nama_departemen' => 'Departemen APU-PPT']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '33', 'nama_departemen' => 'Departemen APU-PPT']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '34', 'nama_departemen' => 'Departemen Pengendalian Gratifikasi & Pemantauan Kepatuhan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '10', 'divisi_id' => '33', 'nama_departemen' => 'Departemen Pengendalian Gratifikasi & Pemantauan Kepatuhan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '57', 'divisi_id' => '35', 'nama_departemen' => 'Unit Kredit Komersial']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '6', 'divisi_id' => '36', 'nama_departemen' => 'Unit KMG']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '6', 'divisi_id' => '37', 'nama_departemen' => 'Unit KMG']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '6', 'divisi_id' => '38', 'nama_departemen' => 'Unit KPR']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '6', 'divisi_id' => '39', 'nama_departemen' => 'Unit KPR']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '12', 'divisi_id' => '40', 'nama_departemen' => 'Unit Bisnis Mikro II']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '58', 'divisi_id' => '41', 'nama_departemen' => 'Unit Bisnis Ritel I']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '58', 'divisi_id' => '42', 'nama_departemen' => 'Unit Bisnis Ritel II']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '9', 'divisi_id' => '43', 'nama_departemen' => 'Departemen Pelaporan Risiko & RMIS']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '9', 'divisi_id' => '43', 'nama_departemen' => 'Departemen Risiko Operasional & Risiko Lainnya']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '9', 'divisi_id' => '43', 'nama_departemen' => 'Departemen Strategi Pencegahan Risiko Fraud']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '9', 'divisi_id' => '44', 'nama_departemen' => 'Departemen Risiko Kredit']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '9', 'divisi_id' => '44', 'nama_departemen' => 'Departemen Risiko Pasar & Likuiditas']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '45', 'nama_departemen' => 'Departemen e-Channel Management']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '45', 'nama_departemen' => 'Departemen Card Management']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '46', 'nama_departemen' => 'Departemen Layanan Operasional']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '46', 'nama_departemen' => 'Unit Contact Centre']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '46', 'nama_departemen' => 'Unit Rekening Massal']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '46', 'nama_departemen' => 'Departemen Account Service']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '47', 'nama_departemen' => 'Departemen Pengelolaan Kas']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '47', 'nama_departemen' => 'Departemen Branch & ATM Network']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '47', 'nama_departemen' => 'Departemen e-Channel & Principle']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '48', 'nama_departemen' => 'Departemen Transaksi Treasury']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '17', 'divisi_id' => '48', 'nama_departemen' => 'Departemen Central Processing']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '49', 'nama_departemen' => 'Departemen Pengelolaan Aset']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '49', 'nama_departemen' => 'Departemen Pemeliharaan']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '49', 'nama_departemen' => 'Departemen Layanan Umum']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '50', 'nama_departemen' => 'Departemen Pengadaan Non-TI']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '50', 'nama_departemen' => 'Unit Administrasi Pengadaan Non-TI']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '51', 'nama_departemen' => 'Departemen Pengadaan TI']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '3', 'divisi_id' => '51', 'nama_departemen' => 'Unit Administrasi Pengadaan TI']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '52', 'nama_departemen' => 'Departemen Pengelolaan Bisnis Lending Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '52', 'nama_departemen' => 'Departemen Pengelolaan Bisnis Funding Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '53', 'nama_departemen' => 'Departemen Branch Quality Assurance']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '54', 'nama_departemen' => 'Departemen Pengelolaan SDM Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '54', 'nama_departemen' => 'Departemen Pengelolaan Kinerja Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '55', 'nama_departemen' => 'Departemen Pengelolaan Jaringan Kantor']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '18', 'divisi_id' => '55', 'nama_departemen' => 'Departemen Pengelolaan Pengadaan Cabang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '56', 'nama_departemen' => 'Unit Manajemen Portofolio']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '56', 'nama_departemen' => 'Unit Pengelolaan Produk & Program']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '57', 'nama_departemen' => 'Departemen Bisnis Dana Ritel']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '57', 'nama_departemen' => 'Departemen Bisnis Komunitas Digital']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '58', 'nama_departemen' => 'Departemen Value Chain & Trade']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '58', 'nama_departemen' => 'Departemen Bisnis Keagenan & Merchant']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '23', 'divisi_id' => '58', 'nama_departemen' => 'Departemen Bisnis E-Banking']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '19', 'divisi_id' => '59', 'nama_departemen' => 'Departemen Pengendalian Kinerja']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '19', 'divisi_id' => '59', 'nama_departemen' => 'Departemen Kebijakan Kinerja & Organisasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '19', 'divisi_id' => '59', 'nama_departemen' => 'Departemen Project Management Office']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '19', 'divisi_id' => '60', 'nama_departemen' => 'Departemen Pengembangan Produk']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '19', 'divisi_id' => '60', 'nama_departemen' => 'Unit Riset']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '19', 'divisi_id' => '60', 'nama_departemen' => 'Departemen Perencanaan Strategis']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '16', 'divisi_id' => '61', 'nama_departemen' => 'Departemen Penyelamatan & Penyelesaian Kredit/Pembiayaan Menengah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '16', 'divisi_id' => '61', 'nama_departemen' => 'Departemen Penyelesaian Kredit/Pembiayaan Hapus Buku']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '16', 'divisi_id' => '62', 'nama_departemen' => 'Departemen Penyelamatan & Penyelesaian Kredit/Pembiayaan Mikro & Ritel']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '16', 'divisi_id' => '62', 'nama_departemen' => 'Departemen Penyelamatan & Penyelesaian Kredit/Pembiayaan Konsumer']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '16', 'divisi_id' => '63', 'nama_departemen' => 'Departemen Lelang']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '16', 'divisi_id' => '63', 'nama_departemen' => 'Departemen Portfolio Management']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '15', 'divisi_id' => '64', 'nama_departemen' => 'Unit Credit Analyst II']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '15', 'divisi_id' => '65', 'nama_departemen' => 'Departemen Penilai Internal']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '15', 'divisi_id' => '65', 'nama_departemen' => 'Unit Credit Analyst Ritel']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '66', 'nama_departemen' => 'Departemen Learning Strategy']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '66', 'nama_departemen' => 'Departemen Learning Operation']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '66', 'nama_departemen' => 'Unit Trainer']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '67', 'nama_departemen' => 'Departemen Anggaran dan Perencanaan Manajemen SDM']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '67', 'nama_departemen' => 'Departemen Strategi & Kebijakan Manajemen SDM']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '67', 'nama_departemen' => 'Departemen Kompensasi & Benefit']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '67', 'nama_departemen' => 'Departemen Manajemen Kinerja']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '68', 'nama_departemen' => 'Departemen Pengembangan Karir']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '68', 'nama_departemen' => 'Departemen Rekrutmen']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '68', 'nama_departemen' => 'Departemen Manajemen Talenta']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '68', 'nama_departemen' => 'Departemen Budaya & Transformasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '69', 'nama_departemen' => 'Unit HCIS']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '69', 'nama_departemen' => 'Departemen Hubungan Industrial']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '2', 'divisi_id' => '69', 'nama_departemen' => 'Departemen Operasional & Administrasi']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '70', 'nama_departemen' => 'Unit Pembiayaan Menengah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '71', 'nama_departemen' => 'Departemen Pembiayaan Kepemilikan Rumah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '71', 'nama_departemen' => 'Departemen Pembiayaan Multi Guna']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '72', 'nama_departemen' => 'Departemen Bisnis Mikro & Gadai']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '72', 'nama_departemen' => 'Departemen Pembiayaan Ritel']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '73', 'nama_departemen' => 'Departemen Dana & Jasa Syariah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '59', 'divisi_id' => '73', 'nama_departemen' => 'Departemen Haji & Umroh']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '74', 'nama_departemen' => 'Unit Development Digital & e-Channel']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '74', 'nama_departemen' => 'Unit Development Core & Supporting System']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '74', 'nama_departemen' => 'Unit Development Enterprise Architecture Integration (EAI)']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '74', 'nama_departemen' => 'Unit Development Enterprise Data Management (EDM)']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '75', 'nama_departemen' => 'Departemen IT Security']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '75', 'nama_departemen' => 'Departemen IT Infrastructure & Data Center']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '75', 'nama_departemen' => 'Departemen IT User Support']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '75', 'nama_departemen' => 'Departemen IT Operation Support']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '75', 'nama_departemen' => 'Departemen IT Helpdesk & Monitoring']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '76', 'nama_departemen' => 'Unit IT Strategy & Finance']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '76', 'nama_departemen' => 'Unit Strategy & Budget']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '76', 'nama_departemen' => 'Unit IT Vendor Management & Quality Assurance']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '76', 'nama_departemen' => 'Unit Policy & Audit Support']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '77', 'nama_departemen' => 'Unit BA Core & Supporting System']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '77', 'nama_departemen' => 'Unit Testing Parameter Management']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '78', 'nama_departemen' => 'Unit PM Digital & e-Channel']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '1', 'divisi_id' => '78', 'nama_departemen' => 'Unit PM Core & Supporting System']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '5', 'divisi_id' => '79', 'nama_departemen' => 'Departemen Likuiditas dan ALMA']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '5', 'divisi_id' => '79', 'nama_departemen' => 'Departemen Banking Management']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '5', 'divisi_id' => '80', 'nama_departemen' => 'Unit Money Market']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '5', 'divisi_id' => '80', 'nama_departemen' => 'Unit Foreign Exchange']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '5', 'divisi_id' => '80', 'nama_departemen' => 'Unit Fixed Income']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '8', 'divisi_id' => '81', 'nama_departemen' => 'Departemen Kesekretariatan dan Protokoler']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '8', 'divisi_id' => '82', 'nama_departemen' => 'Departemen Komunikasi Pemasaran']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '8', 'divisi_id' => '82', 'nama_departemen' => 'Departemen Pemasaran Digital']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '8', 'divisi_id' => '82', 'nama_departemen' => 'Unit Desain Kreatif']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '60', 'divisi_id' => '83', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '61', 'divisi_id' => '84', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '62', 'divisi_id' => '85', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '63', 'divisi_id' => '86', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '64', 'divisi_id' => '87', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '65', 'divisi_id' => '88', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '66', 'divisi_id' => '89', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '67', 'divisi_id' => '90', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '68', 'divisi_id' => '91', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '69', 'divisi_id' => '92', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '70', 'divisi_id' => '93', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '71', 'divisi_id' => '94', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '72', 'divisi_id' => '95', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '73', 'divisi_id' => '96', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '74', 'divisi_id' => '97', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '75', 'divisi_id' => '98', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '76', 'divisi_id' => '99', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '77', 'divisi_id' => '100', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '78', 'divisi_id' => '101', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '79', 'divisi_id' => '102', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '80', 'divisi_id' => '103', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '81', 'divisi_id' => '104', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '82', 'divisi_id' => '105', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '83', 'divisi_id' => '106', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '84', 'divisi_id' => '107', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '85', 'divisi_id' => '108', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '86', 'divisi_id' => '109', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '87', 'divisi_id' => '110', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '88', 'divisi_id' => '111', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '89', 'divisi_id' => '112', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '90', 'divisi_id' => '113', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '91', 'divisi_id' => '114', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '92', 'divisi_id' => '115', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '93', 'divisi_id' => '116', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '94', 'divisi_id' => '117', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '95', 'divisi_id' => '118', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '96', 'divisi_id' => '119', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '97', 'divisi_id' => '120', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '98', 'divisi_id' => '121', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '99', 'divisi_id' => '122', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '100', 'divisi_id' => '123', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '101', 'divisi_id' => '124', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '102', 'divisi_id' => '125', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '103', 'divisi_id' => '126', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '104', 'divisi_id' => '127', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '105', 'divisi_id' => '128', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '106', 'divisi_id' => '129', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '107', 'divisi_id' => '130', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '108', 'divisi_id' => '131', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '109', 'divisi_id' => '132', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '110', 'divisi_id' => '133', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '111', 'divisi_id' => '134', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '112', 'divisi_id' => '135', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '113', 'divisi_id' => '136', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '114', 'divisi_id' => '137', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '115', 'divisi_id' => '138', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '116', 'divisi_id' => '139', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '117', 'divisi_id' => '140', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '118', 'divisi_id' => '141', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '119', 'divisi_id' => '142', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '120', 'divisi_id' => '143', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '121', 'divisi_id' => '144', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '122', 'divisi_id' => '145', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '123', 'divisi_id' => '146', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '124', 'divisi_id' => '147', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '125', 'divisi_id' => '148', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '126', 'divisi_id' => '149', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '127', 'divisi_id' => '150', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '128', 'divisi_id' => '151', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '129', 'divisi_id' => '152', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '130', 'divisi_id' => '153', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '131', 'divisi_id' => '154', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '132', 'divisi_id' => '155', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '133', 'divisi_id' => '156', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '134', 'divisi_id' => '157', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '135', 'divisi_id' => '158', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '136', 'divisi_id' => '159', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '137', 'divisi_id' => '160', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '138', 'divisi_id' => '161', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '139', 'divisi_id' => '162', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '140', 'divisi_id' => '163', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '141', 'divisi_id' => '164', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '142', 'divisi_id' => '165', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '143', 'divisi_id' => '166', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '144', 'divisi_id' => '167', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '145', 'divisi_id' => '168', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '146', 'divisi_id' => '169', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '147', 'divisi_id' => '170', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '148', 'divisi_id' => '171', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '149', 'divisi_id' => '172', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '150', 'divisi_id' => '173', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '151', 'divisi_id' => '174', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '152', 'divisi_id' => '175', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '153', 'divisi_id' => '176', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '154', 'divisi_id' => '177', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '155', 'divisi_id' => '178', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '156', 'divisi_id' => '179', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '157', 'divisi_id' => '180', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '158', 'divisi_id' => '181', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '159', 'divisi_id' => '182', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '160', 'divisi_id' => '183', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '161', 'divisi_id' => '184', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '162', 'divisi_id' => '185', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '163', 'divisi_id' => '186', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '164', 'divisi_id' => '187', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '165', 'divisi_id' => '188', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '166', 'divisi_id' => '189', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '167', 'divisi_id' => '190', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '168', 'divisi_id' => '191', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '169', 'divisi_id' => '192', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '170', 'divisi_id' => '193', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '171', 'divisi_id' => '194', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '172', 'divisi_id' => '195', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '173', 'divisi_id' => '196', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '174', 'divisi_id' => '197', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '175', 'divisi_id' => '198', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '176', 'divisi_id' => '199', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '177', 'divisi_id' => '200', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '178', 'divisi_id' => '201', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '179', 'divisi_id' => '202', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '180', 'divisi_id' => '203', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '181', 'divisi_id' => '204', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '182', 'divisi_id' => '205', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '183', 'divisi_id' => '206', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '184', 'divisi_id' => '207', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '185', 'divisi_id' => '208', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '186', 'divisi_id' => '209', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '187', 'divisi_id' => '210', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '188', 'divisi_id' => '211', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '189', 'divisi_id' => '212', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '190', 'divisi_id' => '213', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '191', 'divisi_id' => '214', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '192', 'divisi_id' => '215', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '193', 'divisi_id' => '216', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '194', 'divisi_id' => '217', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '195', 'divisi_id' => '218', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '196', 'divisi_id' => '219', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '197', 'divisi_id' => '220', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '198', 'divisi_id' => '221', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '199', 'divisi_id' => '222', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '200', 'divisi_id' => '223', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '201', 'divisi_id' => '224', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '202', 'divisi_id' => '225', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '203', 'divisi_id' => '226', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '204', 'divisi_id' => '227', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '205', 'divisi_id' => '228', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '207', 'divisi_id' => '229', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '206', 'divisi_id' => '230', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '208', 'divisi_id' => '231', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '209', 'divisi_id' => '232', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '210', 'divisi_id' => '233', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '212', 'divisi_id' => '234', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '213', 'divisi_id' => '235', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '214', 'divisi_id' => '236', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '215', 'divisi_id' => '237', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '216', 'divisi_id' => '238', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '217', 'divisi_id' => '239', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '218', 'divisi_id' => '240', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '219', 'divisi_id' => '241', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '220', 'divisi_id' => '242', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '221', 'divisi_id' => '243', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '222', 'divisi_id' => '244', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '223', 'divisi_id' => '245', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '224', 'divisi_id' => '246', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '225', 'divisi_id' => '247', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '226', 'divisi_id' => '248', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '227', 'divisi_id' => '249', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '228', 'divisi_id' => '250', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '229', 'divisi_id' => '251', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '230', 'divisi_id' => '252', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '231', 'divisi_id' => '253', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '232', 'divisi_id' => '254', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '233', 'divisi_id' => '255', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '234', 'divisi_id' => '256', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '235', 'divisi_id' => '257', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '236', 'divisi_id' => '258', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '237', 'divisi_id' => '259', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '238', 'divisi_id' => '260', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '239', 'divisi_id' => '261', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '240', 'divisi_id' => '262', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '241', 'divisi_id' => '263', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '242', 'divisi_id' => '264', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '243', 'divisi_id' => '265', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '244', 'divisi_id' => '266', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '245', 'divisi_id' => '267', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '246', 'divisi_id' => '268', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '247', 'divisi_id' => '269', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '248', 'divisi_id' => '270', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '249', 'divisi_id' => '271', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '250', 'divisi_id' => '272', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '251', 'divisi_id' => '273', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '253', 'divisi_id' => '274', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '252', 'divisi_id' => '275', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '254', 'divisi_id' => '276', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '255', 'divisi_id' => '277', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '256', 'divisi_id' => '278', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '257', 'divisi_id' => '279', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '258', 'divisi_id' => '280', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '259', 'divisi_id' => '281', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '260', 'divisi_id' => '282', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '261', 'divisi_id' => '283', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '262', 'divisi_id' => '284', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '263', 'divisi_id' => '285', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '264', 'divisi_id' => '286', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '265', 'divisi_id' => '287', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '266', 'divisi_id' => '288', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '267', 'divisi_id' => '289', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '268', 'divisi_id' => '290', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '269', 'divisi_id' => '291', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '270', 'divisi_id' => '292', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '271', 'divisi_id' => '293', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '272', 'divisi_id' => '294', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '273', 'divisi_id' => '295', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '274', 'divisi_id' => '296', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '275', 'divisi_id' => '297', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '276', 'divisi_id' => '298', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '277', 'divisi_id' => '299', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '278', 'divisi_id' => '300', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '279', 'divisi_id' => '301', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '280', 'divisi_id' => '302', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '281', 'divisi_id' => '303', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '282', 'divisi_id' => '304', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '283', 'divisi_id' => '305', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '284', 'divisi_id' => '306', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '285', 'divisi_id' => '307', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '286', 'divisi_id' => '308', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '287', 'divisi_id' => '309', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '288', 'divisi_id' => '310', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '289', 'divisi_id' => '311', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '290', 'divisi_id' => '312', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '291', 'divisi_id' => '313', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '292', 'divisi_id' => '314', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '293', 'divisi_id' => '315', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '294', 'divisi_id' => '316', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '295', 'divisi_id' => '317', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '296', 'divisi_id' => '318', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '297', 'divisi_id' => '319', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '298', 'divisi_id' => '320', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '299', 'divisi_id' => '321', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '300', 'divisi_id' => '322', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '301', 'divisi_id' => '323', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '302', 'divisi_id' => '324', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '303', 'divisi_id' => '325', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '304', 'divisi_id' => '326', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '305', 'divisi_id' => '327', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '306', 'divisi_id' => '328', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '307', 'divisi_id' => '329', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '308', 'divisi_id' => '330', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '309', 'divisi_id' => '331', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '310', 'divisi_id' => '332', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '311', 'divisi_id' => '333', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '312', 'divisi_id' => '334', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '313', 'divisi_id' => '335', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '314', 'divisi_id' => '336', 'nama_departemen' => 'Layanan Nasabah']);
        DB::table('tbl_master_departemen')->insert(['unit_kerja_id' => '315', 'divisi_id' => '337', 'nama_departemen' => 'Layanan Nasabah']);   
    }    

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbl_master_departemen');
    }
}
